# Generated by Django 5.1 on 2024-11-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivary',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
