# Generated by Django 5.0.6 on 2024-07-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine'),
        ),
    ]
