# Generated by Django 5.1 on 2024-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customeuser_contact_name_companyorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyorder',
            old_name='medicine',
            new_name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='companyorder',
            name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_review',
            name='review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
