# Generated by Django 5.1 on 2024-10-03 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_category_description_medicine_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmancy_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_pharmacy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
