# Generated by Django 5.1 on 2024-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='Image3',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
