# Generated by Django 5.0.6 on 2024-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_wishlist_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
