# Generated by Django 5.0.6 on 2024-08-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='medicine_id',
        ),
    ]
