# Generated by Django 5.1 on 2024-09-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_medicine_companyorder_medicine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='companyorder',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order_review',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
