# Generated by Django 5.1 on 2024-09-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
