# Generated by Django 5.1 on 2024-10-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_prescription_prescription_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity_prescribed',
        ),
    ]
